trigger:
  branches:
    include: [master, test-me-*]

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: asottile-github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v0.0.4

jobs:
- template: job--pre-commit.yml@asottile
